### ISSUE TITLE
설치 과정중 make가 안됩니다

### ISSUE THREAD

**Issue by Kinetic27** [aheui/rpaheui#17]
pypy를 clone하고 pypy안에 rpaheui를 받아서 넣어둔 상태입니다
make를 치자

```
❯ make

echo "VERSION = '`git describe --tags`'" > aheui/version.py
../pypy/rpython/bin/rpython --opt=jit rpaheui.py
process_begin: CreateProcess(NULL, ../pypy/rpython/bin/rpython --opt=jit rpaheui.py, ...) failed.
make (e=2): 지정된 파일을 찾을 수 없습니다.
make: *** [aheui-c] 오류 2
```

라며 오류가 발생합니다

**Comment by youknowone** [comment]
pypy와 rpaheui가 같은 수준에 놓여 있어야 합니다
이를테면 Projects라는 디렉터리가 있으면, Projects/pypy와 Projects/rpaheui가 있어야 합니다.

**Comment by Kinetic27** [comment]
@youknowone E:/pypy, E:/rpaheui 놓고 rpaheui가서 make를 하니

```echo "VERSION = '`git describe --tags`'" > aheui/version.py
../pypy/rpython/bin/rpython --opt=jit rpaheui.py
env: pypy: No such file or directory
make: *** [aheui-c] 오류 127
```

이렇게 오류가 뜹니다..

**Comment by Kinetic27** [comment]
감사합니다

**Comment by youknowone** [comment]
문제는 해결되셨나요? 윈도를 배려하지 않은 makefile이어서 윈도에서는 좀 문제가 되었을거 같네요. Makefile 보고 내용을 윈도에 맞게 실행하면 될거 같아요

**Comment by Kinetic27** [comment]
열심히 makefile 공부해봐야겠네요 감사합니다
