### ISSUE TITLE
재현 가능한 빌드 방법을 readme에 추가해 주세요.

### ISSUE THREAD

**Issue by Bubbler-4** [aheui/rpaheui#18]
혼자서 pyenv에서 여러 가지 버전을 가지고 삽질해본 결과 아래의 순서대로 실행하니 됐습니다.

Prerequisite: pyenv 설치 (https://github.com/pyenv/pyenv)

```bash
pyenv install 2.7.18
pyenv global 2.7.18
pyenv install pypy2.7-7.0.0-src # 약 2시간 이상 걸림
RPYTHON=$(pyenv root)/pypy2.7-7.0.0-src/rpython/bin/rpython make
```

Note: RPython 7.1.0 이상에서는 str와 bytes를 섞어 쓰는 것이 금지되었기 때문에 빌드가 되지 않습니다.

**Comment by youknowone** [comment]
확인 감사합니다 :bow:
